name: greenville
description: "Greenville Template"
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: '>=3.3.3 <4.0.0'

flutter_gen:
  integrations:
    flutter_svg: true

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  #  package_info: ^2.0.2
  http: ^1.1.0
  flutter_spinkit: ^5.2.0
  device_info_plus: ^9.0.2
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  go_router: ^13.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  permission_handler: ^11.1.0
  flutter_asset_generator: ^1.0.2
  custom_info_window: ^1.0.1
  logger: ^2.0.1
  clipboard: ^0.1.3
  webview_flutter: ^4.4.2
  flutter_native_splash: ^2.3.1
  share_plus: ^7.2.1
  intl: ^0.19.0
  url_launcher: ^6.1.12
  purchases_flutter: ^6.4.0
  animated_text_kit: ^4.2.2
  mobile_scanner: ^3.5.5
  gal: ^2.3.0
  dio: ^5.4.1
  fluttertoast: ^8.2.4


flutter_native_splash:
  #color: "#63133f"
  android: true
  android_12:
    image: assets/images/android12splash.png
    # App icon background color.
    icon_background_color: "#8d245b"
    color: "#8d245b"
  ios: true
  web: false

  background_image: "assets/images/GPTSplashBackground.png"
  image: "assets/images/splashlogo.png"
  ios_content_mode: "center"
  web_image_mode: "top"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/aiseeklauncher.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/json/organisations.json
    - assets/json/night_style.json
    - assets/json/map_style.json
    - assets/images/brighton.jpg
    - assets/images/brighton_background.jpg
    - assets/images/destination_map_marker.png
    - assets/images/driving_pin.png
    - assets/images/friend1.jpg
    - assets/images/friend2.jpg
    - assets/images/GPTSplashBackground.png
    - assets/images/GPTSplashLogo.png
    - assets/copyright.html
    - assets/images/poweredby.png
    - assets/images/aiseeklogo.png
    - assets/images/aiseeklogoondark.png
    - assets/images/android12splash.png
    - assets/images/bottomnav_home.png
    - assets/images/bottomnav_settings.png
    - assets/images/bottomnav_history.png
    - assets/images/bottomnav_help.png
    - assets/images/bottomnav_home_active.png
    - assets/images/bottomnav_settings_active.png
    - assets/images/bottomnav_history_active.png
    - assets/images/bottomnav_help_active.png
    - assets/images/lightbulb.png
    - assets/images/rightarrow.png
    - assets/images/focus.png



  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.13.0"
